### ISSUE TITLE
fanc map (OSError: [Errno 16] Device or resource busy)

### ISSUE THREAD

**Issue by saraebell** [vaquerizaslab/fanc#104]
I am encountering this error message when I run **fanc map** on some fastq files.
'**OSError: [Errno 16] Device or resource busy**'

It appears that the **.sam files are still being generated** and the job completes without failure (ie SLURM job Completes without Failure or Error No) but I am unsure why when I look at the # STDERR file (shown below) I get the OSError: [Errno 16] Device or resource busy. I do not know if I can trust these .sam files to continue with the rest of the fanc commands. 

![Screen Shot 2022-03-20 at 10 03 15 AM](https://user-images.githubusercontent.com/82554600/159173975-a674ccc0-b539-4627-8887-30939a853871.png)

![Screen Shot 2022-03-20 at 10 04 04 AM](https://user-images.githubusercontent.com/82554600/159173984-03d28aaa-b384-4f46-9987-ec54fcf12aa0.png)

**Comment by kaukrise** [comment]
Hi, you mentioned in the other thread that this was solved? In any case, the error indicates a problem with the network file system, and does not appear to be FAN-C specific. Please close this issue if it is no longer a problem.
