### ISSUE TITLE
fanc to_cooler multi-resolution fails because .cool binsize is None

### ISSUE THREAD

**Issue by iagooteroc** [vaquerizaslab/fanc#109]
Hello,
I am trying to obtain a multi-resolution .mcool file with the `to_cooler` functionality. With `--no-multi` it works, but when trying to create the multi-resolution, `zoomify_cooler` is called with the .cool file, which has a `None` .binsize value. This causes the following error:
```
Traceback (most recent call last):
  File "/mnt/netapp2/uscmg_aplic/3_environments/python/fan-c/bin/fanc", line 127, in <module>
    Fanc()
  File "/mnt/netapp2/uscmg_aplic/3_environments/python/fan-c/bin/fanc", line 93, in __init__
    command([sys.argv[0]] + sys.argv[option_ix:], log_level=log_level, verbosity=verbosity)
  File "/mnt/netapp2/uscmg_aplic/3_environments/python/fan-c/lib/python3.10/site-packages/fanc/commands/fanc_commands.py", line 2063, in to_cooler
    to_cooler(hic, output_file, balance=norm, multires=multi, resolutions=resolutions,
  File "/mnt/netapp2/uscmg_aplic/3_environments/python/fan-c/lib/python3.10/site-packages/fanc/compatibility/cooler.py", line 150, in to_cooler
    cooler.zoomify_cooler(single_path, multi_path, resolutions, chunksize, nproc=threads)
  File "/mnt/netapp2/uscmg_aplic/3_environments/python/fan-c/lib/python3.10/site-packages/cooler/reduce.py", line 805, in zoomify_cooler
    resn, pred, mult = get_multiplier_sequence(resolutions, base_resolutions)
  File "/mnt/netapp2/uscmg_aplic/3_environments/python/fan-c/lib/python3.10/site-packages/cooler/reduce.py", line 468, in get_multiplier_sequence
    resn = np.array(sorted(bases.union(resolutions)))
TypeError: '<' not supported between instances of 'int' and 'NoneType'
```
It doesn't matter if I specify the resolutions or not.
Is there a workaround or fix to this? Thank you.

**Comment by kaukrise** [comment]
Hi, if I understand correctly, you are supplying a Cooler (`.cool`) file to `to-cooler`. `to-cooler` is meant to convert FAN-C files to Cooler format - for converting Cooler single to multi-resolution files, I would assume [Cooler](https://github.com/open2c/cooler) tools are the best place to look?

**Comment by iagooteroc** [comment]
Hi, sorry I didn't explain myself correctly. I'm using to_cooler with a fan-c generated .hic like this:
`fanc to_cooler sample.hic sample.mcool`
Then, by looking at the function's [code](https://github.com/vaquerizaslab/fanc/blob/e5ce8dd7e67053480e6e078d89b6c73946fdae33/fanc/compatibility/cooler.py#L37), I see that a .cool file is generated at first using 
`cooler.create_cooler(cool_uri=single_path, bins=region_df, pixels=pixel_iter(), ordered=False)`
to then zoomify it using
`cooler.zoomify_cooler(single_path, multi_path, resolutions, chunksize, nproc=threads)`
That's the origin of the error I'm getting, since `zoomify_cooler` uses the .binsize of the `.cool` file you provide to it, and the `.cool` file generated by fan-c has a .binsize value of `None` for a reason I don't know.
Could it be that something changed in the cooler library in an update for it to be failing now?
Thank you for your time.

**Comment by kaukrise** [comment]
Thanks for explaining the details. Give me a bit and I'll try to reproduce on a clean installation with FAN-C sample data

**Comment by kaukrise** [comment]
I am unable to reproduce the issue on the FAN-C example data, version `0.9.23`, Python `3.10.3`.

Are you, by any chance, supplying the fragment-level Hi-C file to `to-cooler`? You need to provide a **binned** Hi-C file, preferably one with high resolution, so that the coarsening would work.

**Comment by iagooteroc** [comment]
Indeed I am supplying the fragment-level Hi-C instead of a binned one haha
So sorry for the troubles and thank you for your help!

**Comment by kaukrise** [comment]
No worries, I am improving the command's help text to clarify this. Thanks for getting back to me!
