### ISSUE TITLE
fanc compartments

### ISSUE THREAD

**Issue by Kurotakid** [vaquerizaslab/fanc#11]
Hi,
According to your instructions, I am trying to generate AB enrichment profile heat maps. I would like to change the bin size to a finer binning. However, it did not work. My command entered is below:

$ fanc compartments -e test.png -p 10 20 30 40 50 60 70 80 90 100 test_1mb.hic test.ab

When I did this analysis without "-p" option, I could generate a heat map successfully.
Thank you in advance for your cooperation!
Best,
Daisuke

**Comment by kaukrise** [comment]
Hi there, this is a limitation of having a space-separated list of percentiles (in your command, the tool interprets the hic file as another percentile). For a future implementation I'll change this to a comma-separated list.

For now, try changing the argument order:

```
fanc compartments -p 10 20 30 40 50 60 70 80 90 100 -e test.png test_1mb.hic test.ab
```

**Comment by Kurotakid** [comment]
Thank you so much! I could generate a heat map with finner resolution.

**Comment by Kurotakid** [comment]
Hi,
Although I did AB enrichment analysis using the "fanc compartments" tool with "-g" option  to properly orient the eigenvector, I got the following error:

```
fanc compartments -g /home/kurotaki/Indices/Mus_musculus_Index/UCSC/mm10/Sequence/WholeGenomeFasta/genome.fa -p 5 10 15 20 25 30 35 40 45 50 55 60 65 70 75 80 85 90 95 100 -e test_1MB.ps test.hic@1000000 test_1MB.ab
2020-02-29 14:33:49,176 INFO Computing AB compartment matrix
/home/kurotaki/miniconda3/lib/python3.6/site-packages/fanc/compatibility/juicer.py:583: RuntimeWarning: divide by zero encountered in true_divide
  return np.array(vectors[resolution]) / sf
AB  81% (18 of 22) |############################       | Elapsed Time: 0:00:49 ETA:   0:00:09/home/kurotaki/miniconda3/lib/python3.6/site-packages/numpy/lib/function_base.py:2526: RuntimeWarning: Degrees of freedom <= 0 for slice
  c = cov(x, y, rowvar)
AB 100% (22 of 22) |###################################| Elapsed Time: 0:00:57 Time:  0:00:57
Buffers 100% (4 of 4) |################################| Elapsed Time: 0:00:00 Time:  0:00:00
Expected 100% (180296 of 180296) |#####################| Elapsed Time: 0:00:14 Time:  0:00:14
2020-02-29 14:35:07,476 INFO Generating profile...
2020-02-29 14:35:23,160 INFO Using GC content to orient eigenvector...
2020-02-29 14:35:53,186 INFO 1
Traceback (most recent call last):
  File "/home/kurotaki/miniconda3/bin/fanc", line 124, in <module>
    Fanc()
  File "/home/kurotaki/miniconda3/bin/fanc", line 90, in __init__
    command([sys.argv[0]] + sys.argv[option_ix:], log_level=log_level, verbosity=verbosity)
  File "/home/kurotaki/miniconda3/lib/python3.6/site-packages/fanc/commands/fanc_commands.py", line 3848, in compartments
    genome=genome_file)
  File "/home/kurotaki/miniconda3/lib/python3.6/site-packages/fanc/architecture/compartments.py", line 299, in enrichment_profile
    ev = self.eigenvector(exclude_chromosomes=exclude_chromosomes, *args, **kwargs)
  File "/home/kurotaki/miniconda3/lib/python3.6/site-packages/fanc/architecture/compartments.py", line 191, in eigenvector
    chromosome_sequence = genome[chromosome_sub].sequence
  File "/home/kurotaki/miniconda3/lib/python3.6/site-packages/fanc/regions.py", line 1000, in __getitem__
    key = names.index(key)
ValueError: '1' is not in list
Closing remaining open files:T9D7XA...done
```
When I did this analysis without "-g" option, I could generate an enrichment profile.
Could you help me to overcome this problem?

Best,
Daisuke

**Comment by kaukrise** [comment]
Hi,

it looks like the chromosome names in your FASTA do not match with those in your Juicer Hi-C object. To confirm, can do run the following commands and paste the output here?
```
cat /home/kurotaki/Indices/Mus_musculus_Index/UCSC/mm10/Sequence/WholeGenomeFasta/genome.fa | grep ">"
```

and

```
python -c 'import fanc; hic = fanc.load("test.hic@1000000"); print(hic.chromosomes());'
```


Thanks

**Comment by Kurotakid** [comment]
Thank you for your reply. I got the results as follows:
```
[kurotaki ~/HiC]$cat /home/kurotaki/Indices/Mus_musculus_Index/UCSC/mm10/Sequence/WholeGenomeFasta/genome.fa | grep ">"
>chr10
>chr11
>chr12
>chr13
>chr14
>chr15
>chr16
>chr17
>chr18
>chr19
>chr1
>chr2
>chr3
>chr4
>chr5
>chr6
>chr7
>chr8
>chr9
>chrM
>chrX
>chrY
[kurotaki ~/HiC]$python -c 'import fanc; hic = fanc.load("test.hic@1000000"); print(hic.chromosomes());'
['1', '2', '3', '4', '5', '6', '7', '8', '9', '10', '11', '12', '13', '14', '15', '16', '17', '18', '19', 'M', 'X', 'Y']
```
I think chromosome names are different between my genome FASTA and the hic file.
Best,
Daisuke

**Comment by kaukrise** [comment]
Yes, that's what I thought might be the issue. Juicer trims the "chr" off the chromosome names in the hic object. If you have used the same FASTA file for creating the Juicer matrix, the easiest thing to do is to manually remove the "chr" from the FASTA headers and try with the new FASTA file.

**Comment by Kurotakid** [comment]
Thanks. 
I have successfully generated an enrichment profile heat map. 
I have an additional question. The pattern of EV percentile cutoff in the heat map is strange. Please see the figure below:
![test_1MB2](https://user-images.githubusercontent.com/43644902/75870478-5d0fd480-5e4e-11ea-8b8d-2d702ce94873.jpg)
I think the first bar on the left is too high. Is this a problem?

**Comment by kaukrise** [comment]
This is not a problem. It is a FAN-C feature to plot the EV cutoffs - the most extreme percentiles can sometimes be associated with extreme eigenvector entries. In our experience, these often stem from noisy or low mappability genomic regions.

Your profile looks great! If there were strange patterns, such as an unexpected depletion of contacts among the most active regions, the EV pattern might help you identify potential issues.

**Comment by Kurotakid** [comment]
Thank you so much! 
FAN-C is very nice to plot the AB enrichment profile. I've always wanted to make this!
Daisuke

**Comment by kaukrise** [comment]
Thanks a lot!
