### ISSUE TITLE
File format for fanc expected

### ISSUE THREAD

**Issue by 14stutzmanav** [vaquerizaslab/fanc#112]
Hi there,

I've been successfully using fanc for a while now, but today I encountered a strange error that leads me to believe I'm interpreting something incorrectly. I have some hic files that I converted from juicer .hic files to .cool to fanc. hic files. I would like to use fanc expected to look at these matrices but I am unable to do so.  

My input command is as follows:
```
fanc expected -p plot-chr2L.png $converts/wt-merged-fanc.hic distDecay-chr2L.txt
```

I'm repeatedly getting the following error:
```
2022-05-18 16:53:20,986 INFO FAN-C version: 0.9.20b0
Traceback (most recent call last):
  File "/nas/longleaf/home/alexisv7/.local/bin/fanc", line 127, in <module>
    Fanc()
  File "/nas/longleaf/home/alexisv7/.local/bin/fanc", line 93, in __init__
    command([sys.argv[0]] + sys.argv[option_ix:], log_level=log_level, verbosity=verbosity)
  File "/nas/longleaf/home/alexisv7/.local/lib/python3.8/site-packages/fanc/commands/fanc_commands.py", line 4191, in expected
    with fanc.load(input_file, mode='a', tmpdir=tmp) as matrix:
  File "/nas/longleaf/home/alexisv7/.local/lib/python3.8/site-packages/fanc/tools/load.py", line 90, in load
    return gr_load(file_name, *args, **kwargs)
  File "/nas/longleaf/home/alexisv7/.local/lib/python3.8/site-packages/genomic_regions/regions.py", line 195, in load
    raise ValueError("File type not recognised ({}).".format(file_name))
ValueError: File type not recognised (converts/hwt-3LW-wing-merged-fanc.hic).
```

It notes that the file type is not recognized; however, other fanc functions (i.e. fanc compartments and fanc aggregate) work with the exact same files. Am I interpreting something incorrectly and need a different file type than the one I have?

Thanks for any help you can provide!

Alexis

**Comment by kaukrise** [comment]
Hi,

thanks for reporting this. I am not sure what is going on - the command looks fine.

Could you please 

1. Upgrade FAN-C to the latest version
2. Run the command in debug mode, without plot (`fanc -vvv expected $converts/wt-merged-fanc.hic distDecay-chr2L.txt`)
3. Try to open the file in a Python console (`python` and then `import fanc; fanc.load("$converts/wt-merged-fanc.hic distDecay-chr2L.txt")`)

Also, it would help if you were more specific about the conversion. Why did you convert to `.cool` first, and then to FAN-C? At what resolution did you export the matrices?

And one more thing - the command implies you are trying to plot the decay of `chr2L`, but you did not add the `-c chr2L` parameter - was that intentional?

Thanks!
Kai

**Comment by kaukrise** [comment]
Also, just of curiosity: you mentioned that you have Juicer Hi-C files. Have you tried using them with `fanc expected` directly? Something like

```
fanc expected -p plot-chr2L.png $converts/wt-merged-juicer.hic@100kb distDecay-chr2L.txt
```

**Comment by kaukrise** [comment]
Hi,

thanks a lot for your feedback - the `fanc expected` command has a `-N` option for plotting the "raw" contact values. However, I just tested it and it is broken! My apologies. I already implemented a fix, so the plot would respect the `-N` parameter - would you be so kind to test it?

[fanc-0.9.23b5.tar.gz](https://github.com/vaquerizaslab/fanc/files/8741786/fanc-0.9.23b5.tar.gz)

(install directly with `pip install fanc-0.9.23b5.tar.gz`)

I tested it on a 4DN Juicer file (`4DNFI3JYF9VS`) with and without the `-N` parameter and it appears to work fine now.

Raw contacts:

```bash
fanc expected -N -c 1 -p expected_raw.png 4DNFI3JYF9VS.hic@500kb expected_raw.txt
```

Normalised contacts:
```bash
fanc expected -N -c 1 -p expected.png 4DNFI3JYF9VS.hic@500kb expected.txt
```

By the way, the values reported in the expected values text file were not subject to this bug.

**Comment by kaukrise** [comment]
Actually, reading your comment again, I think I might have misunderstood your question.

The expected values are calculated from the average, normalised, **observed** values from all pixels at a certain distance. Using the `-N` parameter the same average contacts are calculated, but without normalisation.

If you just want to plot the Hi-C signal with distance to a **specific** genomic locus, maybe you are looking for something like the virtual 4C plot? https://fan-c.readthedocs.io/en/latest/api/modules/plotting.html#fanc.plotting.Virtual4CPlot

**Comment by kaukrise** [comment]
Cool, glad we could sort that out and thanks a lot for testing the `-N` option!
