### ISSUE TITLE
hic file loading error to juicebox

### ISSUE THREAD

**Issue by wushyer** [vaquerizaslab/fanc#127]
Hi, I am currently using 0.9.24 version to handle my hic library. I found the hic file produced by fanc can not be loaded into juicebox. Any idea about this? Thanks

Best,
Shuangyang

**Comment by kaukrise** [comment]
Please see here:

https://github.com/vaquerizaslab/fanc/issues/111#issuecomment-1126792444

**Comment by wushyer** [comment]
Thanks, I have a further question.
Below is the compartment analysis based on 250kb. The result totally
changes when I use genome.fa in *fanc compartments.*
Any idea about this?

Thanks. Regards
Shuangyang

###command line
fanc compartments -v fanc-at_250kb.ev.txt fanc-at_250kb.ab
fanc compartments -g Aa.chr.fa -v fanc-at_250kb.ev.gc.txt fanc-at_250kb.ab


####result

(tools3) ***@***.*** compartment-result]$ head -n 5
fanc-at_250kb.ev.gc.txt
chr1 1 250000 A 0.0643612808104578 .
chr1 250001 500000 A 0.05485647432031034 .
chr1 500001 750000 A 0.05780317818227389 .
chr1 750001 1000000 B -0.03969476884965929 .
chr1 1000001 1250000 B -0.06539520933110446 .
(tools3) ***@***.*** compartment-result]$ head -n 5
fanc-at_250kb.ev.txt
chr1 1 250000 B -0.06436128081045779 .
chr1 250001 500000 B -0.05485647432031034 .
chr1 500001 750000 B -0.05780317818227385 .
chr1 750001 1000000 A 0.0396947688496593 .
chr1 1000001 1250000 A 0.06539520933110442 .


[image: image.png]


kaukrise ***@***.***> 于2022年9月19日周一 08:54写道：

**Comment by liz-is** [comment]
I think Kai already answered this question for you in issue #128. If you have further follow-up queries I'd suggest you ask there, since this issue is already closed.
