### ISSUE TITLE
Issue using -r option for fanc insulation.

### ISSUE THREAD

**Issue by joshuak94** [vaquerizaslab/fanc#136]
Dear FANC team,

Thank you for the great tool! I ran into an issue where when I call
`fanc insulation hic/hic_file.hic hic/output.insulation -w 100kb 250kb 500kb 1Mb -r chr18:53656551-57425762`
I get the following error:
`fanc insulation: error: Output file cannot be empty when choosing default output format!`

However, when I call the same command without the region option, it runs fine without a problem.

Any insight is appreciated!

Thank you!

**Comment by joshuak94** [comment]
Note that adding `-o bed` to the command will allow it to run again.

**Comment by kaukrise** [comment]
Sorry about that, can you try this version?

[fanc-0.9.26b2.tar.gz](https://github.com/vaquerizaslab/fanc/files/10093807/fanc-0.9.26b2.tar.gz)

```
pip install fanc-0.9.26b2.tar.gz
```

Thanks!
Kai
