### ISSUE TITLE
fancplot gene usage

### ISSUE THREAD

**Issue by joshuak94** [vaquerizaslab/fanc#138]
Hello! I'm trying to visualize some data and have the gene annotations alongside it. I obtained the gtf annotation files from Gencode. However, when I plot the annotation using -p gene, I only get an empty panel. I can use -p layer to see red and blue bars of different lengths, so it seems to be parsing the file correctly, but the -p gene is not correctly outputting the genes. Is there an example file/usage I can use to reference and troubleshoot my scenario?

Thank you!

**Comment by kaukrise** [comment]
Hi, do you get any warnings when trying to plot the GTF file? I just tried with a Gencode file I had lying around and it worked alright. Here is a subset you can test (after unzipping):

[gencode.v35.annotation.10k_on_chr6.gtf.zip](https://github.com/vaquerizaslab/fanc/files/10268120/gencode.v35.annotation.10k_on_chr6.gtf.zip)

```bash
fancplot chr6:43501526-44501526 -p gene gencode.v35.annotation.10k_on_chr6.gtf
```
This will plot every individual feature, so I'd recommend grouping and changing the label:

```bash
fancplot chr6:43501526-44501526 -p gene -g gene_id --label-field gene_name gencode.v35.annotation.10k_on_chr6.gtf
```

You should be seeing this:

![gene_plot](https://user-images.githubusercontent.com/1540112/208661871-f5480e69-dc5f-47c0-8025-f9ce9b406ddc.png)

In general, working with GTF can be really slow. FAN-C supports Tabix (via the great [pybedtools](https://daler.github.io/pybedtools/)). Here is an example that shows how to use it: https://www.biostars.org/p/289819/#365871

**Comment by joshuak94** [comment]
Thank you for the quick response! No warnings output.

I assume it has to do with the fact that I'm using a custom genome? To try and make fanc work better for Capture HiC data, I subset the mm10 genome to the region which was enriched in the capture protocol and used that as my "reference genome" for the alignment/filtering/normalization. So my reference genome is a 4Mb portion of chromosome 18. Could this cause any issues

**Comment by kaukrise** [comment]
You could upload the file here and I'll take a look

**Comment by joshuak94** [comment]
[chr18_zeroed_genes_deletion.zip](https://github.com/vaquerizaslab/fanc/files/10268304/chr18_zeroed_genes_deletion.zip)
[chr18_hard_del.zip](https://github.com/vaquerizaslab/fanc/files/10268312/chr18_hard_del.zip)

Here are the files. It's just a GTF and GFF file (I thought converting to GFF3 might help). 

The reference is called chr18_hard_del.fa, and the "chromosome name" is chr18_hard_del. The coordinates start at 0 and go to ~3.7Mb, but the enriched region was from ~53Mb - 57.7Mb.

For the annotations, I took the gencode annotation gtf and extracted the annotations which fall within my region. Then I "zeroed" them to match the coordinates of the reference file (subtracting the start and end positions by 53Mb).

**Comment by kaukrise** [comment]
You deleted the exon entries from the GTF. Have a look at the gene plot help:

```
  -f FEATURE_TYPES [FEATURE_TYPES ...], --feature-types FEATURE_TYPES [FEATURE_TYPES ...]
                        Feature types to be plotted. By default only exons are shown.
```

You can use `-f` to plot gene entries instead:

```
fancplot chr18_hard_del:1-3mb -p gene -f gene --label-field gene_name chr18_zeroed_genes_deletion.gtf
```

Which will give you this

![chr18_hard_del_gene_plot](https://user-images.githubusercontent.com/1540112/208668712-c77e68a7-f061-4537-bcbb-3b3eb112dd6c.png)

**Comment by joshuak94** [comment]
Thank you for your help!

One more quick question. If I wanted to bin the colors on a heatmap, aka values 1-10 get one color, 10-20 get another color, 20+ gets a third color, is this possible with fancplot?

**Comment by kaukrise** [comment]
Hi, for plots as customised as the one you are describing, you would have to use the [Python plotting API](https://fan-c.readthedocs.io/en/latest/api/plot/plot_basics.html). This is something you could achieve with a custom colormap in [matplotlib](https://matplotlib.org/) - I found an example of this [here](https://medium.datadriveninvestor.com/creating-a-discrete-colorbar-with-custom-bin-sizes-in-matplotlib-50b0daf8dd46). Matrix-based plots in FAN-C provide the `plot.colorbar` attribute, and `add_colorbar` function that might help.
