### ISSUE TITLE
UnicodeDecodeError in fanc loops

### ISSUE THREAD

**Issue by jmsanper** [vaquerizaslab/fanc#14]
Hi,
I'm trying to annotate loops from a 10kb-resolution hic file and I get the following:

2020-03-05 10:32:30,848 INFO Calculating intra-chromosomal expected values...
2020-03-05 10:32:30,865 INFO Done.
2020-03-05 10:32:31,091 INFO Initial parameter values: p=2, w=5
2020-03-05 10:32:31,091 INFO Obtaining bias vector...
Expected N/A% (0 of 203545187) |         | Elapsed Time: 0:00:00 ETA:  --:--:--
Expected   0% (1 of 203545187) |         | Elapsed Time: 0:00:00 ETA:  00:00:00
Expected   1% (2035452 of 203545187) |   | Elapsed Time: 0:03:18 ETA:   5:28:03
...
Expected 100% (203545187 of 203545187) |#| Elapsed Time: 5:19:24 Time:  5:19:24
2020-03-05 15:53:47,327 INFO Done.
2020-03-05 15:53:47,328 INFO Processing chr1-chr1
2020-03-05 15:57:01,662 INFO using 10 processes
Traceback (most recent call last):
  File "/home/ska/jsanper/miniconda3/lib/python3.7/site-packages/gridmap/job.py", line 249, in execute
    self.ret = self.function(*self.args, **self.kwlist)
  File "/home/ska/jsanper/miniconda3/lib/python3.7/site-packages/fanc/peaks.py", line 1357, in process_matrix_segment_intra
    max_w = msgpack.loads(data)
  File "/home/ska/jsanper/miniconda3/lib/python3.7/site-packages/msgpack_numpy.py", line 198, in unpackb
    return _unpackb(packed, **kwargs)
  File "msgpack/_unpacker.pyx", line 195, in msgpack._cmsgpack.unpackb
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xf0 in position 14: invalid continuation byte

(this error is repeated for many positions and finally...)

TypeError: a bytes-like object is required, not 'UnicodeDecodeError'
Closing remaining open files:loops/HiC_danRer10_48h_ctcf_r10kb.loops...done

I've tried with other hic files getting the same. And these same hic files worked perfectly for other tools like insulation, boundaries, pca, compare, fancplot, etc.
My python environment is 3.7.6.
Could you give please me a clue of what's happening?
Thank you in advance.
Best,

Jose Maria

**Comment by jmsanper** [comment]
Sorry, the command was just:
$ fanc loops HiC.10000.hic HiC.10000.loops -t 10
I used slurm with 10 cpus in a single node.

**Comment by kaukrise** [comment]
Hi, thanks for the detailed bug report! msgpack for Python recently had a major version change which caused issues elsewhere, maybe this is the problem here, too. I'll look into it!

**Comment by kaukrise** [comment]
Hi again!

I was unable to reproduce your issue with the sample data, so I have a couple of questions:

- Which version of FAN-C are you running? `fanc -V`
- What version of `msgpack` and `msgpack-numpy` are you running? `pip freeze | grep msgpack`
- What are your locale variables? `locale`
- Could you generate the sample data (see [here](https://vaquerizaslab.github.io/fanc/getting_started.html#example-analysis)) and then run the loop annotation on the file `output/hic/binned/fanc_example_10kb.hic` in your environment? `fanc loops -t 4 output/hic/binned/fanc_example_10kb.hic loops.test`

Thank you!

**Comment by jmsanper** [comment]
Hi Kai,
This is the info you're asking for:
- FAN-C version: 0.8.17
- msgpack-numpy version: 0.4.4.3
- Locale variables: 
LANG=es_ES.UTF-8
LC_CTYPE="es_ES.UTF-8"
LC_NUMERIC="es_ES.UTF-8"
LC_TIME="es_ES.UTF-8"
LC_COLLATE="es_ES.UTF-8"
LC_MONETARY="es_ES.UTF-8"
LC_MESSAGES="es_ES.UTF-8"
LC_PAPER="es_ES.UTF-8"
LC_NAME="es_ES.UTF-8"
LC_ADDRESS="es_ES.UTF-8"
LC_TELEPHONE="es_ES.UTF-8"
LC_MEASUREMENT="es_ES.UTF-8"
LC_IDENTIFICATION="es_ES.UTF-8"
LC_ALL=

I'll run the sample data and then tell you.
Thank you!

Jose Maria

**Comment by kaukrise** [comment]
Hi, first things first, could you please upgrade to the lastest FAN-C version before you run the test?

```
pip install --upgrade fanc
```

Also, I would need the complete output of the command `pip freeze | grep msgpack`, please, not just the `msgpack-numpy` version.

Thanks!

**Comment by jmsanper** [comment]
Of course! Now fanc version is 0.8.25

$ pip freeze | grep msgpack
msgpack==1.0.0
msgpack-numpy==0.4.4.3
msgpack-python==0.5.6

running sample with new version

**Comment by jmsanper** [comment]
Hi again!
Finally I solved the problem updating msgpack-python:
$ conda install -c anaconda msgpack-python
Now the program has generated the loops.
Thank you!

**Comment by kaukrise** [comment]
That's great, thanks for letting us know and for providing the anaconda fix!
