### ISSUE TITLE
A/B compartments different in different chromosomes 

### ISSUE THREAD

**Issue by nibhelim** [vaquerizaslab/fanc#145]
Hi Folks, I am running the command 'fanc compartments -g mouse_mm9.fa WT.hic@250000 WT_250k.ab' to make the .ab file. then 'fanc compartments -g mouse_mm9.fa -d WT.bed WT.ab' to make the bed file. 
problem is that the A/B orientation is different depending on the chromosome, in some chr the heterochromatin is A in others is B.
I thought that using the genome would avoid this but no. any help is appreciated!

**Comment by kaukrise** [comment]
Hi, compartment calling is a complex task, and `-g` is just a (poor) heuristic to orient the eigenvector - especially at higher resolutions. There is no alternative solution implemented in FAN-C, so you'll have to manually orient the EV.
