### ISSUE TITLE
fanc compare almost empty matrices

### ISSUE THREAD

**Issue by jmsanper** [vaquerizaslab/fanc#15]
I'm using fanc compare to compare hic matrices at 10kb resolution with KR normalization, either with fold-change and difference. This is the command for example for difference:

$ fanc compare HiC-1.res10kb.KR.hic HiC-2.res10kb.KR.hic HiC-diff.res10kb.KR.hic -c diff -S

I get a file more heavy than the original ones, however when I pick a region to show with fancplot, it is empty. If I do fanc dump, I only get information of a tiny subset of bin pairs, but the difference in those contacts seems to be well calculated. For example, for chr1 I obtain 7602181 pairs for HiC-1, 15870999 pairs for HiC-2, but only 41 pairs for HiC-diff.

Am I doing something wrong?

Thank you,

Jose Maria

**Comment by kaukrise** [comment]
Hi, I don't think you're doing anything wrong, the command looks fine from what I can see. I have received a similar bug report before, but could not reproduce it so far.

What version of FAN-C did you use to generate the matrices?
Is it the same version used to generate the difference matrix?
Can you see signal in each of the two original matrices with `fancplot`?

**Comment by jmsanper** [comment]
I've run version 0.8.27 both for generating the original matrices from juicer hic files (using fanc from-juicer) and for generating the difference matrix. And yes, the two original matrices show good signal in every region I've looked at.

**Comment by kaukrise** [comment]
Hey, I found a couple of matrices that also have the issue you are seeing, which allowed me to identify the problem. FAN-C incorrectly identified the majority of regions as "invalid" and hence masked them.

The good news is that all the data is there, it is just hidden, and the fix is straightforward. I will run some tests to ensure the fix did not break anything else, and then I'll let you know how to fix your comparison matrices.

**Comment by jmsanper** [comment]
Great, I look forward to hearing it, thank you!

**Comment by kaukrise** [comment]
I have now pushed the version with the fix to PyPi (`0.8.28`). To fix your matrices, please first upgrade via `pip` (or GitHub, if you prefer):

```
pip install --upgrade fanc
```

And ensure that you are running the latest version

```
fanc -V
```

Then you can use the following command to fix your matrix, just run it in the same directory as your difference Hi-C file:

```
python -c 'import fanc; m = fanc.load("HiC-diff.res10kb.KR.hic", mode="a"); m._update_mappability();'
```

It will take a while to complete, but once it is done could you please verify that the matrix now looks alright? Thanks!

**Comment by jmsanper** [comment]
Hi! The new matrix is completely fine, thank you very much!

**Comment by kaukrise** [comment]
Great, thanks for letting me know!
