### ISSUE TITLE
fanc map multi-threads and memory issue

### ISSUE THREAD

**Issue by xunchen85** [vaquerizaslab/fanc#154]
Hello,

I like fanc very much. I have also successfully tested it with the example data. 

I submitted a job with 20 CPU using the following fanc map command to analyze a HIC dataset with a > 60Gb ziped fastq file. bwa/0.7.17 and sambamba/0.8.0 were loaded. The job start without any issues and slowly run the alignment using bwa.

I mean really slow, like 24hrs only got 3Gb SAM output file. When I checked the compute node, I found only one CPU was used by bwa and another CPU used by fanc script. I further checked the generated intermediate SAM file, BWA was ran with a single CPU in the header. Do you know how I could address it or did I do something wrong?

Command:
_fanc map -m 25 -s 10 -t 20 -tmp --split-fastq_

Meanwhile, when I ran fanc map without the --split-fastq parameter, the job could fully use 20 CPUs, but it was always stopped by the memory issue even with a requested 120Gb ram.

I really hope you could help solve the problem.

Thanks,
Xun

**Comment by kaukrise** [comment]
Hi,

I am not sure why `--split-fastq` does not seem to use the full 20 threads you requested - I tested it locally and the threads are propagated properly to the sub-commands for the split FASTQ files. Here is the relevant section in the code:

https://github.com/vaquerizaslab/fanc/blob/354401e52ba2320e6b1ba0d3b5aab3541d31c9f3/fanc/commands/fanc_commands.py#L467-L469

Regarding the run without the `--split-fastq` flag: The parallelisation is done by spawning multiple `bwa` processes, each of which loads the entire BWA index into memory, which is probably too much with 20 threads. Try 8 and see if you get a difference, please. Alternatively, you can try to memory-map the BWA index using `--memory-map` command (it is labeled as a Bowtie2 feature, but can be applied to BWA). However, I encountered frequent crashed when attempting this with BWA on my system.

**Comment by xunchen85** [comment]
Hi,

Thanks for your kind help. I got this error after I reduced to 10 threads and it failed again. This is my command and log file. It generated an empty bam in the end. Could you help? 

I also have few questions here:
1) Is it a big difference if I do --split-fastq or not regarding the speed and ram?

2) Will the situation changed if I switch to use bowtie2 for the alignment? Then I could re-index my reference for it.

3) btw, if I understand correctly, I could also use the validated.pairs generated by HiC-pro to use as the input for fanc. Could I get similar results if I do that?

Thanks,
Xun

Command:
fanc map -m 25 -s 10 -t 10 -tmp /home/xchen85/scratch/juicer_run/raw_fastq/test_R1.fastq.gz /home/xchen85/scratch/fanc_run/reference/hg38_HBV_v2.fasta test_R1.bam

error logs:

2023-04-16 13:10:05,845 INFO FAN-C version: 0.9.25
2023-04-16 13:12:56,300 INFO Starting mapping for /tmp/tmpat4718ze.gz
2023-04-16 13:12:56,388 INFO Starting to output alignments to intermediate SAM file /tmp/tmps8h17hqz/intermediate.sam
Traceback (most recent call last):
  File "/home/xchen85/ENV3.8_fanc/bin/fanc", line 127, in <module>
    Fanc()
  File "/home/xchen85/ENV3.8_fanc/bin/fanc", line 93, in __init__
    command([sys.argv[0]] + sys.argv[option_ix:], log_level=log_level, verbosity=verbosity)
  File "/home/xchen85/ENV3.8_fanc/lib/python3.8/site-packages/fanc/commands/fanc_commands.py", line 437, in map
    map.iterative_mapping(input_file, output_file, mapper, threads=threads,
  File "/home/xchen85/ENV3.8_fanc/lib/python3.8/site-packages/fanc/map.py", line 981, in iterative_mapping
    raise Exception(exc)
Exception: Traceback (most recent call last):
  File "/home/xchen85/ENV3.8_fanc/lib/python3.8/site-packages/fanc/map.py", line 645, in _iterative_mapping_worker
    sam_file, unmapped_file = mapper.map(input_file, output_folder=output_folder)
  File "/home/xchen85/ENV3.8_fanc/lib/python3.8/site-packages/fanc/map.py", line 218, in map
    raise RuntimeError('Mapping had non-zero exit status {}. {}'.format(ret, error_message))
RuntimeError: Mapping had non-zero exit status -9. [M::bwa_idx_load_from_disk] read 0 ALT contigs
[M::process] read 100000 sequences (10638330 bp)...


2023-04-16 17:42:25,758 INFO FAN-C version: 0.9.25

sambamba 0.8.0
 by Artem Tarasov and Pjotr Prins (C) 2012-2020
    LDC 1.10.0 / DMD v2.080.1 / LLVM6.0.1 / bootstrap LDC - the LLVM D compiler (0.17.4)

sambamba-sort: not enough data in stream
2023-04-16 17:42:25,842 WARNING sambamba failed, falling back to pysam/samtools
Traceback (most recent call last):
  File "/home/xchen85/ENV3.8_fanc/bin/fanc", line 127, in <module>
    Fanc()
  File "/home/xchen85/ENV3.8_fanc/bin/fanc", line 93, in __init__
    command([sys.argv[0]] + sys.argv[option_ix:], log_level=log_level, verbosity=verbosity)
  File "/home/xchen85/ENV3.8_fanc/lib/python3.8/site-packages/fanc/commands/fanc_commands.py", line 638, in sort_sam
    output_file = sort_natural_sam(sam_file, output_file, threads=threads)
  File "/home/xchen85/ENV3.8_fanc/lib/python3.8/site-packages/fanc/tools/files.py", line 574, in sort_natural_sam
    pysam.sort('-n', '-o', output_file, sam_file)
  File "/home/xchen85/ENV3.8_fanc/lib/python3.8/site-packages/pysam/utils.py", line 69, in __call__
    raise SamtoolsError(
pysam.utils.SamtoolsError: 'samtools returned with error 1: stdout=, stderr=samtools sort: failed to read header from "test_R1.bam"\n'
slurmstepd: error: Detected 1 oom-kill event(s) in StepId=36333774.batch. Some of your processes may have been killed by the cgroup out-of-memory handler.

**Comment by kaukrise** [comment]
It looks like one of your mapping processes ran out of memory allotted by Slurm. I don't use Slurm myself, so it is hard for me to debug, but how much memory are you providing the job with?

1. This should not make a big difference, as files are internally partitioned anyways
2. This might improve the memory issue (with (`--memory-map`), but the overall mapping is probably going to be slower
3. Yes, you can also use that directly with `fanc pairs`

**Comment by xunchen85** [comment]
Thanks for your reply.

I have provided 10 CPUs with a total of 120G RAM. I have also tried bowtie2 and it also failed. 

I may just use HiC-pro for the alignment and feed the valid pairs to fanc for the following analysis. 

Thanks,
Xun
