### ISSUE TITLE
About output of observed/expected matrix value

### ISSUE THREAD

**Issue by GleeenSIBS** [vaquerizaslab/fanc#156]
Can fanc compute the observed/expected matrix value and get an output file like txt? Which command?

**Comment by kaukrise** [comment]
https://fan-c.readthedocs.io/en/latest/fanc-executable/fanc-generate-hic/fanc_helpers.html#fanc-dump-export-hic-objects-to-text-file

**Comment by GleeenSIBS** [comment]
Thanks!
