### ISSUE TITLE
Bias vector

### ISSUE THREAD

**Issue by nponts** [vaquerizaslab/fanc#165]
Hi,
Thanks for the awesome tool.
Is there a way to extract the bias vector from an already normalized FAN-C .hic (or to do it on the fly)?
Thanks!

N.

**Comment by kaukrise** [comment]
https://fan-c.readthedocs.io/en/latest/api/modules/hic.html?highlight=bias_vector#fanc.hic.Hic.bias_vector

```python
import fanc

hic = fanc.load('/path/to/hic.file')
v = hic.bias_vector()
```

**Comment by kaukrise** [comment]
This is just the Python shell's way of abbreviating information - `v` contains the entire bias vector. If you want to export the vector to a file, for example, you could do this:

```python
import numpy as np

np.savetxt('/path/to/bias_vector_file.txt', v)

```

**Comment by nponts** [comment]
Thank you so much for your help and your patience with my ignorance :)
Cheers!

**Comment by sotuamax** [comment]
Hello, 

How can I set bias_vector for a my file after running balancing function. 
I tried with: 

`hic_file.bias_vector(vector = np_array_vector)`

the 'hic_file' is <class 'fanc.compatibility.cooler.CoolerHic'>. 

However, it does not work. 

Could you clarify? 

Best,
