### ISSUE TITLE
Loops Exporting to BEDPE

### ISSUE THREAD

**Issue by Drosophilid** [vaquerizaslab/fanc#17]
Hi,
I have successfully detect the loops but have issues while exporting them into BEDPE format (got empty file). I have used command as below:
3.7.0/bin/fanc loops chrX.filtered.noSinglets.merged.loops -b chrX.merged.bedpe

Thanks

**Comment by kaukrise** [comment]
Hi,

I tested the command on some sample data, and it works fine in my setup. Is it possible that your file is, in fact, empty, because of the filtering you applied? To check, could you send me the output of

```
python -c "import fanc; loops = fanc.load('chrX.filtered.noSinglets.merged.loops'); print(len(loops))"
```

please?

**Comment by lubna290** [comment]
Thanks for the quick reply, I have attached my sample loops file below.

Thanks[
[chrX.filtered.noSinglets.merged.loops.gz](https://github.com/vaquerizaslab/fanc/files/4707628/chrX.filtered.noSinglets.merged.loops.gz)

](url)

**Comment by kaukrise** [comment]
Yes, there are no valid loops in that file. I would advise you to try adjusting your filter settings to be less strict. Getting the settings right can be really difficult, in our experience.

**Comment by lubna290** [comment]
I'm working on Drosophila genome and this is the command (write below) how I get the loops. Could you please suggest me if I can try some other parameters.
3.7.0/bin/fanc loops chrX.hic chrX.loops -t 16
3.7.0/bin/fanc loops chrX.loops chrX.filtered.loops --rh-filter -d 5 -o 5
3.7.0/bin/fanc loops chrX.filtered.loops chrX.filtered.noSinglets.merged.loops -j --remove-singlets
3.7.0/bin/fanc loops chrX.filtered.noSinglets.merged.loops -b chrX.filtered.noSinglets.merged.loops.bedpe

Thanks

**Comment by kaukrise** [comment]
First of all, I'd like to note that the default `loops` filtering parameters have been optimised for human and mouse genomes. Drosophila loops can have a very different appearance in Hi-C maps, and will likely require some experimentation to get the settings right.

If you haven't done so, read the original [HICCUPS article](https://pubmed.ncbi.nlm.nih.gov/25497547/) to really understand the different neighbourhoods and procedures.

My recommendation is 

1. Run `fanc loops chrX.hic chrX.loops -t 16` as previously. This just annotates each pixel with information we need for filtering later on
2. Choose a set of loops from the original Hi-C matrices that you can clearly see by eye. You are going to use these to check if your settings work (you can use `fancplot` for this)
3. Run `fanc loops chrX.loops chrX.filtered.loops` with very lenient parameters. For example `--enrichment 1.25 --fdr 0.2 --observed 5 --min-distance 5`
4. Run `fancplot <region> -p square chrX.filtered.loops` for each of the loops regions you identified in 2. This allows you to see which pixels have passed the filtering step
5. Adjust the parameters in 3. If you have removed the "loop" pixels, choose less stringent cutoffs. If there are too many pixels outside of your identified loops, especially clusters of pixels, choose more stringent cutoffs.
6. Repeat 3-5 until you found a suitable set of parameters. When you are getting close, you can also fine-tune individual cutoffs. The most important ones will likely be `--enrichment-donut` and `--fdr-donut`, but also have a look at `--mappability` to reduce noise in your results.
7. Once you have a set of parameters that will filter out non-loop pixels, but leave in the loops you are interested in, you can run the merge and singlet removal steps (which will further reduce noise)

I hope that helps!
