### ISSUE TITLE
License invokes the GPL but restricts the applicability of the GPL which violates the GPL

### ISSUE THREAD

**Issue by rekado** [vaquerizaslab/fanc#18]
Hi,

the license says that for non-commercial use the GPL version 2 applies, but that for commercial use another license must be obtained.

This creates a conflict with the text of the GPL, which grants the rights to use the software for any purpose --- including commercial use.  Furthermore, the GPL cannot be extended with additional restrictions:

> 6. [...] You may not impose any further restrictions on the recipients' exercise of the rights granted herein. [...]

Does this mean that I may not use fanc under the terms of the GPL at all?  This, sadly, prevents inclusion of fanc in free software distributions, such as Debian or GNU Guix.

I would be happy if you could clarify this and perhaps remove the misleading references to the GPL when the license actually is intended to restrict usage contrary to the guarantees granted by the GPL. 

Thanks!

**Comment by kaukrise** [comment]
Thank you for your question. The use of the 'Academic Public Licence' has been suggested to us by Max Planck Innovation, which we have asked for a comment on your question. I'll update this thread as soon as we receive a reply.

**Comment by kaukrise** [comment]
Hello, sorry for the delay. The response we received from Max Planck Innovation is:

> From our point of view there is no need to change the license text as there is no dependency to the GPL license. GPL is only mentioned as a reference "Similarly to GPL 2.0..:" and "By modeling the GPL 2.0..", thus this creates no conflict to us.

I hope that answers your question, otherwise I'd be happy to forward any additional questions you have.

**Comment by rekado** [comment]
Thank you for asking for clarification and getting back to me.

I still think it is unfortunate to reference the GPL when one of the core features of the GPL does not apply, but it is good to see your clarification here.  Thank you!
