### ISSUE TITLE
hic files format after the fanc auto pipeline

### ISSUE THREAD

**Issue by Knetsy** [vaquerizaslab/fanc#184]
Hello,

I have successfully run `fanc auto` on my fastq files and I got indeed .hic files. I would like to use the `plotgardener` R package to plot Hi-C data but I got an error that says "Hi-C magic string is missing, does not appear to be a hic file." 
Could you please indicate me how to have proper .hic files? I tried the `fanc subset` command to extract contacts from a specific chromosome and then try to load this .hic files using the `plotgardener` R package and I got the same error.

Thank you.

Best,

Deborah

**Comment by kaukrise** [comment]
Juicer and FAN-C just happen to use the same file extension. FAN-C output is not compatible with tools that expect a Juicer `.hic` format. You can either try to convert to a Juicer file using `fanc to-juicer` on the `.pairs` file from FAN-C, or directly use a Juicer preprocessing pipeline.
