### ISSUE TITLE
Documentation page down

### ISSUE THREAD

**Issue by mphan236** [vaquerizaslab/fanc#25]
Hi, 

Your doc site https://vaquerizaslab.github.io/fanc is down. Would you mind letting me know when it'll be back on? That'd be really awesome. thanks!

Best,

**Comment by kaukrise** [comment]
Hi, we are aware of the issue and are working on a fix. It does not seem to be down for everyone, so we are still trying to figure out why some people can see it.

We recently renamed the `master` branch to `main`, and only found out afterwards that GitHub apparently still does not support branches other than `master` for automatic pages generation.

I will keep you posted.

**Comment by kaukrise** [comment]
It seems to be back up for me - can you give it a try?

**Comment by mphan236** [comment]
yes it's back up for me too. Thanks! :+1:
