### ISSUE TITLE
A/B compartments calling: Chromosome {} not found in genome. Are you using the correct genome file?

### ISSUE THREAD

**Issue by mdozmorov** [vaquerizaslab/fanc#31]
Hi,
I followed the instructions to call A/B compartments. First, created the AB compartment matrix file from a .hic file, then used it to extract .bed coordinates of A/B compartments. 

As soon as I supply the genome to refine A/B calls, the function breaks. I use the same genome that was used to create the .hic file. The error raised by `compartments.py` is:
```
ValueError: Chromosome {} not found in genome. Are you using the correct genome file?
```
My genome has chromosome names as `chr1` etc. It seems FAN-C uses numeric notation for chromosome names; manually reformatting the genome FASTA file to have numerical chromosome names solved the problem. It is OK if one is aware of chromosome name requirements. I can't recall any place in the documentation. Suggesting adding this.

**Comment by kaukrise** [comment]
Hi, FAN-C does not rename chromosomes - Juicer does. It removes the "chr" prefix when you generate the `.hic` file.

I'll probably add something to the docs anyways.

**Comment by mdozmorov** [comment]
Thank you, didn't know that. Yes, a couple of lines in the documentation about chromosome name convention would help.
