### ISSUE TITLE
--chromosomes in fanc hic

### ISSUE THREAD

**Issue by biozzq** [vaquerizaslab/fanc#33]
Dear @kaukrise 

I found that when I set the argument `--chromosomes 1,2,3` when running `fanc hic`, it always gave me an error as following:

`fanc hic -b 50k -r 0.25 -n -m KR -s input.statistics -d 0 --reset-filters --chromosomes 1,2,3 input_fragment_level.hic input_50K_KR.hic`
2020-12-11 20:09:42,281 INFO FAN-C version: 0.9.9
usage: fanc hic [-h] [-b BIN_SIZE] [-l FILTER_LOW_COVERAGE]
                [-r FILTER_LOW_COVERAGE_RELATIVE] [-a] [-d FILTER_DIAGONAL]
                [--marginals-plot MARGINALS_PLOT] [--reset-filters]
                [--downsample DOWNSAMPLE] [--subset SUBSET] [-i] [-k] [-n]
                [-m NORM_METHOD] [-w] [-c] [--only-inter] [-s STATS]
                [--statistics-plot STATS_PLOT]
                [--chromosomes CHROMOSOMES [CHROMOSOMES ...]] [-f]
                [-t THREADS] [--deepcopy] [-tmp]
                input [input ...]
fanc hic: error: the following arguments are required: input

Sincerely,
Zheng zhuqing

**Comment by kaukrise** [comment]
Hi, please try:

```
fanc hic --chromosomes 1 2 3 -b 50k -r 0.25 -n -m KR -s input.statistics -d 0 --reset-filters input_fragment_level.hic input_50K_KR.hic
```

Chromosome names are not comma-separated for this parameter and the command parser gets confused if it is the last command.

**Comment by biozzq** [comment]
Thank you. It works now according to your suggestion.
