### ISSUE TITLE
bin_size for LinePlot

### ISSUE THREAD

**Issue by jessakay** [vaquerizaslab/fanc#35]
Thanks for providing such a flexible plotting interface with fancplot! When trying to visualize bigWig tracks, I noticed that the `bin_size` parameter seems to have no effect for `LinePlot` despite it being a parameter. After looking into the source code it seems that it's essentially ignored. Although it appears that the legacy `BigWigPlot` class did have routines for changing bin sizes, I was unable to find much related documentation.

Could you please share if there are any plans of re-implementing the capacity to set bin sizes at run-time or if not, how to properly use the deprecated `BigWigPlot`?

**Comment by kaukrise** [comment]
Hi, thanks a lot for your nice words!

I'm sorry, the `bin_size` parameter seems to have fallen through the cracks at some point. I have now uploaded a new version (`0.9.10`) that restores the binning functionality in both the API and the command line plotting. Also, it now works for bar plots, too!

You can use it like this:

```python
import fanc
import fanc.plotting as fancplot

bw = fanc.load("/path/to/file.bw")
p = fancplot.LinePlot(bw, bin_size=10000)
p.plot('chr1:10mb-11mb')
p.show()
```

Alternatively (and only in the API for now), you can also use the `bins` parameter, which will bin regions into exactly `bins` number of bins.

```python
import fanc
import fanc.plotting as fancplot

bw = fanc.load("/path/to/file.bw")
p = fancplot.LinePlot(bw, bins=20)
p.plot('chr1:10mb-11mb')
p.show()
```

On the command line, use the `--bin-size` parameter like this:

```
fancplot chr1:10mb-11mb -p line /path/to/file.bw --bin-size 10kb
```

Let me know how it goes!

Cheers,

Kai

**Comment by jessakay** [comment]
Works great! Thank you for the quick fix
