### ISSUE TITLE
Can fanc help for generating a chromosome-level genome assembly?

### ISSUE THREAD

**Issue by Huangtianyu-caas** [vaquerizaslab/fanc#36]
Hi there,

I am currently working on the assembly of a pacbio-sequenced genome data, and I the next step of my work is using my HiC data to generate a chromosome-level genome.

Is there any possibility that I can use fanc to generate a chromosome-level genome assembly based on my HIC data?

My best,
Tianyu

**Comment by kaukrise** [comment]
Hi, FAN-C does not support genome assembly from Hi-C data. I am also not up to date on the current state of suitable tools, so unfortunately I cannot make a recommendation.
