### ISSUE TITLE
ModuleNotFoundError: No module named 'fanc.tools.sambam'

### ISSUE THREAD

**Issue by papelypluma** [vaquerizaslab/fanc#37]
Hi fanc developers,

I'm attempting to install fanc following the instructions as documented in the https://fan-c.readthedocs.io/en/latest/getting_started.html#installation. Installation seems to complete successfully (conda environment on Python 3.6 and 3.7), but invoking fanc --version or fanc -h raises an error "ModuleNotFoundError: No module named 'fanc.tools.sambam'". I'm wondering if there's a roundabout to this problem.

Thank you.

**Comment by kaukrise** [comment]
Hi,

I am not using conda myself, so I have not encountered this issue. My best guesses are:

- The Python paths are not configured correctly
- The installation did not complete successfully
- The conda environments are somehow mixed up / not activated properly

If this cannot be resolved within conda, maybe you could consider an installation in a clean Python virtual environment outside of conda?

**Comment by papelypluma** [comment]
Hi @kaukrise. Thanks for the advice! I tried installing fanc in a Python virtual env, and it's now working. My bad, I'm sorry. I think I missed one step in the installation. I should've invoked setup.py install earlier (I guess). Installation in virtual env and conda are now both working. Thanks for the help!
