### ISSUE TITLE
Error when generating pairs file from 4Dnucleome file: AttributeError: 'NoneType' object has no attribute 'Lock'

### ISSUE THREAD

**Issue by irenemota** [vaquerizaslab/fanc#39]
Hi, 

I am trying to generate  a pairs file using `fanc pairs` from a 4Dnucleome formatted file. I am using it like this:
`fanc pairs  -g /data/slow_disk/share/imotago/LowCoverage/merge_nodups_files/test_files/mm10_noScaffolds.fa -r MboI  -s stats_SF1_XX_pairs.txt  --statistics-plot stats_plot_SF1_XX.png  SF1_XX_formatted.pairs  merge_nodups_final_SF1_XX_rep1_2_pairs.pairs 
`

 and I am getting the following error:

```
Traceback (most recent call last):
  File "/home/imotago/.local/bin/fanc", line 124, in <module>
    Fanc()
  File "/home/imotago/.local/bin/fanc", line 90, in _init_
    command([sys.argv[0]] + sys.argv[option_ix:], log_level=log_level, verbosity=verbosity)
  File "/home/imotago/.local/lib/python3.6/site-packages/fanc/commands/fanc_commands.py", line 994, in pairs
    pairs.add_read_pairs(sb, threads=threads, batch_size=batch_size)
  File "/home/imotago/.local/lib/python3.6/site-packages/fanc/pairs.py", line 1496, in add_read_pairs
    for fi1, fi2 in self._read_pairs_fragment_info(read_pairs, batch_size=batch_size, threads=threads):
  File "/home/imotago/.local/lib/python3.6/site-packages/fanc/pairs.py", line 1275, in _read_pairs_fragment_info
    monitor = Monitor()
  File "/home/imotago/.local/lib/python3.6/site-packages/fanc/pairs.py", line 137, in _init_
    self.generating_pairs_lock = manager.Lock()
AttributeError: 'NoneType' object has no attribute 'Lock'
Closing remaining open files:merge_nodups_final_SF1_XX_rep1_2_pairs.pairs...doneO6X9UQ...done
```
My input file looks like this:

```
## pairs format v1.0 
#shape: upper triangle
#genome_assembly: mm10
#chromsize: chr1 195471971
#chromsize: chr2 182113224
#chromsize: chr3 160039680
#chromsize: chr4 156508116
#chromsize: chr5 151834684
#chromsize: chr6 149736546
#chromsize: chr7 145441459
#chromsize: chr8 129401213
#chromsize: chr9 124595110
#chromsize: chr10 130694993
#chromsize: chr11 122082543
#chromsize: chr12 120129022
#chromsize: chr13 120421639
#chromsize: chr14 124902244
#chromsize: chr15 104043685
#chromsize: chr16 98207768
#chromsize: chr17 94987271
#chromsize: chr18 90702639
#chromsize: chr19 61431566
#chromsize: chrX 171031299
#chromsize: chrY 91744698
#chromsize: chrM 16299
#columns: readID chr1 pos1 chr2 pos2 strand1 strand2
K00302:125:HC335BBXY:3:2105:5142:9877/2K00302:125:HC335BBXY:3:2105:5142:9877/1 chr1 3000015 chr1 3012702 + -
K00302:113:H3L3TBBXY:4:1127:15168:40367/1K00302:113:H3L3TBBXY:4:1127:15168:40367/2 chr1 3000027 chr1 3001190 + -
K00302:113:H3L3TBBXY:4:1209:5457:10563/1K00302:113:H3L3TBBXY:4:1209:5457:10563/2 chr1 3000041 chr1 3022118 + -
K00302:125:HC335BBXY:3:2110:28321:9631/2K00302:125:HC335BBXY:3:2110:28321:9631/1 chr1 3000109 chr1 3559591 + -
```
Do you know how I can solve this issue? 
Thanks in advance!

**Comment by kaukrise** [comment]
Hi there, thank you for the well-formatted issue! I could reproduce the issue and found a fix that works on my sample pairs file. The version with the fix should now be available on Pypi (`0.9.11`). Can you update with

```
pip install --upgrade fanc
```

and try again, please?

And one more note, the statistics plot only really works if you did the filtering with FAN-C, as any information about filtered pairs is missing from 4DN files.

Also, if you downloaded from the 4DN portal directly, maybe there is a matching Juicer `hic` file you can use? It would save you some trouble with the conversion...

**Comment by irenemota** [comment]
Hi, 

Thank you very much, it fixed the problem.

There is indeed a Juicer .hic file that I can use, however I wanted to generate again the hic files using fanc in order to increase the low_coverage removal percentage for my downstream analysis. Maybe there is a more efficient way of doing that?

Thank you

**Comment by kaukrise** [comment]
One way that is probably faster is this:

1. Download the Juicer `.hic` file from 4DN
2. Convert it to FAN-C format using `fanc hic --deepcopy <SF1_XX.hic>@<resolution> <SF1_XX.fanc>` (replace file names in `<>` with actual file names and `<resolution>` with your desired resolution from the Juicer file)
3. Filter low-coverage matrix bins using `fanc hic --filter-low-coverage-relative 0.2 <SF1_XX.fanc>` (replace the cutoff with whatever you require)
4. (optional, but recommended) Re-normalise the converted file using `fanc hic -n <SF1_XX.fanc>`. If you are removing a lot of bins in the previous step, the normalisation might no longer be accurate. Additionally, while the converted file is already normalised by Juicer, FAN-C scales the sum of contact values in each bin to 1 (roughly interpretable as "contact probabilities"), which makes some downstream analyses, especially comparisons, simpler.

I hope this helps!

**Comment by irenemota** [comment]
Thank you very much!
