### ISSUE TITLE
argument order and documentation of fanc fragments

### ISSUE THREAD

**Issue by balwierz** [vaquerizaslab/fanc#4]
```
usage: fanc fragments [-h] [-c CHROMOSOMES [CHROMOSOMES ...]]
                      input re_or_bin_size output
```

If I am not mistaken the order of arguments to `fanc fragments` does matter.
`--chromosomes` has `nargs='+'`, so it cannot be passed before the remaining 3 unnamed arguments as the help message suggests. It can only go at the end.

And I had to guess that the list of chromosomes should be space-separated. My first guess was a coma. So `CHROMOSOMES` isn't actually a list of chromosomes, but a single chromosome and should be renamed.

Also: It is not clear to me which restriction enzymes are supported.

**Comment by kaukrise** [comment]
Thanks for pointing this out, I'll clarify this in the help text and the documentation.
All restriction enzyme from Biopython.Restriction are supported: http://biopython.org/DIST/docs/cookbook/Restriction.html

**Comment by kaukrise** [comment]
The argument is now a comma-separated list. I might convert similar arguments like this in the future.
