### ISSUE TITLE
Should duplication be removed in HiC-Pro valid pairs

### ISSUE THREAD

**Issue by biozzq** [vaquerizaslab/fanc#40]
Dear all,

I was wondering that whether the duplication in the valid pairs used in `fanc pairs` should be removed. That means which file should be used in `fanc pairs`, validPairs interactions or allValidPairs in the Hic-Pro results? Thank you.

Best wishes,
Zheng zhuqing

**Comment by kaukrise** [comment]
I am not a HiC-Pro expert, but according to [their docs](https://github.com/nservant/HiC-Pro/blob/master/doc/MANUAL.md#browsing-the-results) the `.allValidPairs` file contains the `validPairs` merged from all read chunks, so you probably want that?

**Comment by biozzq** [comment]
Dear @kaukrise 

Yes, the `.allValidPairs` file contains the `validPairs` merged from all read chunks, however, the PCR duplication has been removed in `.allValidPairs` but not in `validPairs`. Thus, I do not know which file should be used as input for `fanc pairs` as you just said the pairs file in https://fan-c.readthedocs.io/en/latest/fanc-executable/fanc-generate-hic/fanc_modular_steps.html#fanc-pairs-generating-and-filtering-read-pairs. Thanks for your help.
![image](https://user-images.githubusercontent.com/15704257/104724080-26436400-576b-11eb-9ca0-cc736db565a0.png)

Best wishes,
Zheng zhuqing

**Comment by liz-is** [comment]
It is typically recommended to remove PCR duplicates. If you wish to do this, you can either use the `.allValidPairs` file that has already been filtered to remove these, or you can use the `validPairs` file and use the `--filter-pcr-duplicates` option for `fanc pairs` (see documentation on the page that you linked above).

**Comment by biozzq** [comment]
Thanks for your help.
