### ISSUE TITLE
Dump to txt with API

### ISSUE THREAD

**Issue by mphan236** [vaquerizaslab/fanc#56]
Hi Kai, 

Quick question, I saw that there is a possibility to 'dump' the hic object to a  a txt format (like so <bin1><tab><bin2><tab><weight>) using the cmd line helper tools, and I was wondering if there's a way to do this from within Python using the API? That'd be really convenient!

Thanks!!

Mikie

**Comment by kaukrise** [comment]
Hi Mikie,

there isn't anything built in, but you could wrap the command line dump in a `subprocess` call?

```python
import subprocess
subprocess.call(['fanc', 'dump', '/path/to/file.hic', '/path/to/matrix.txt', '/path/to/regions.txt'])
```

Alternatively, have a look at the [implementation in the repo](https://github.com/vaquerizaslab/fanc/blob/3c32c52ed1fa4b50085938038e71ead9bb826c5a/fanc/commands/fanc_commands.py#L2214). It covers a lot of use cases, but in essence you can dump regions like this:

```python
with open('regions.bed', mode='w') as o:
    for r in hic.regions(lazy=True):
        o.write("{}\t{}\t{}\t{}\n".format(r.chromosome, r.start, r.end, r.ix))
```

and (nonzero) matrix entries like this:

```python
with open('contacts.txt', mode='w') as o:
    for edge in matrix.edges(lazy=True):
        o.write("{}\t{}\t{}\n".format(edge.source, edge.sink, edge.weight))
```

**Comment by mphan236** [comment]
i'll give it a try. thanks a lot for the suggestions!
