### ISSUE TITLE
extract significant contacts

### ISSUE THREAD

**Issue by gorliver** [vaquerizaslab/fanc#57]
Hi Kaukrise,
I wonder is there a tool or API to assign significance (p-value or FDR) to each pixel and extract all the significant contracts?

Thank you,
Gorliver

**Comment by kaukrise** [comment]
Hi, please have a look at the peak calling functionality, this also annotates pixels with FDR values. 

https://fan-c.readthedocs.io/en/latest/fanc-executable/fanc-analyse-hic/loops.html
https://fan-c.readthedocs.io/en/latest/api/analyse/loops.html

It is based on the great HICCUPS algorithm from this paper: https://www.cell.com/fulltext/S0092-8674(14)01497-4. Note that the FAN-C implementation is CPU-based and slower than the original variant. If speed is of the essence (for example for large matrices), please have a look here: https://github.com/aidenlab/juicer/wiki/HiCCUPS

**Comment by gorliver** [comment]
Hi Kaukrise,
Thank you for your prompt reply.
I tried the `fanc loops` using the example data (SRR4271982_chr18_19 data) but cannot get a bedpe file.
Here is my command line:
```
fanc loops -f output/hic/fanc_example.hic output/loops/fanc_example_25kb.loop -t 48
fanc loops -f output/loops/fanc_example_25kb.loop output/loops/fanc_example_25kb_filterd.loop --rh-filter -d 5 -o 5
fanc loops -f output/loops/fanc_example_25kb_filterd.loop  output/loops/fanc_example_25kb_merged.loop -j --remove-singlets
fanc loops output/loops/fanc_example_25kb_merged.loop  -b output/loops/fanc_example_25kb_merged_filter.bedpe
```
Each step runs well and no error message arose.
It seems not a filter problem as I cannot get a bedpe from any .loop file.

**Comment by kaukrise** [comment]
25kb resolution is too big for loop calling. Please follow the guide that I linked to [above](https://fan-c.readthedocs.io/en/latest/fanc-executable/fanc-analyse-hic/loops.html).

Please note that loop calling is far from trivial. There are a lot of parameters that need to be optimised specifically for each matrix, and there are no simple default settings that will "just work", at least not in FAN-C. You will need to familiarise yourself with the HICCUPS algorithm from the original manuscript to understand the different parameters, neighbourhood types, and outputs.

If you want to access the FDR values and other annotations for each pixel, you need to do so through the Python API, which I also linked to [above](https://fan-c.readthedocs.io/en/latest/api/analyse/loops.html).

**Comment by gorliver** [comment]
Hi Kaukrise,
Thank you very much for the links.
I'm closing the issue now.
