### ISSUE TITLE
Did fancplot use the KR norm when juicer hic file was used

### ISSUE THREAD

**Issue by biozzq** [vaquerizaslab/fanc#59]
Dear all

I want to plot normalised matrix data, but the following command does not appear to work.

`fancplot chr10:40mb-43mb --pdf-text-as-font -o AH-1_AH-2.pdf -p mirror -d 2mb AH-1-7-13.hic@50kb@KR AH-2-8-14.hic@50kb@KR`

![捕获](https://user-images.githubusercontent.com/15704257/120440519-36747c80-c3b6-11eb-95e5-3d14f60a5732.PNG)

Sincerely,
Zheng zhuqing

**Comment by kaukrise** [comment]
Hi, can you please be a bit more specific as to what you were expecting to happen instead? Since the plot is generated, I am not sure where exactly the issue is. Thank you!

**Comment by biozzq** [comment]
Dear @kaukrise 

Sorry for the unclear description. According to the range of colorbar, i think the data used to generate above plot has not been balanced by KR. Thus, I do not know if `fancplot` has normalised matrix data on the fly? 

Best,
Zhengzhuqing

**Comment by kaukrise** [comment]
Thank you for the clarification. I think everything works as expected here, it looks as though you are plotting the normalised data. 

Unlike FAN-C, the Juicer KR norm scales the matrix entries back up to the original number of valid pairs. Thus the FAN-C values for a KR normalised matrix are between `0` and `1` (which is useful for comparing matrices), but the Juicer values are in the range of values of the uncorrected matrix. You can test this by plotting the unnormalised data, which should look a bit different to the KR normalised data:

```
fancplot chr10:40mb-43mb -p mirror -d 2mb AH-1-7-13.hic@50kb@NONE AH-2-8-14.hic@50kb@NONE
```

**Comment by biozzq** [comment]
Dear @kaukrise 

Thank you. Yes, the plots generated by `@NONE` and `@KR` are indeed different. More, if I want to make the two matrix more comparable, I should not use the Juicer KR norm, but should change to use any other tools, such as `FAN-C`, `HiCExplorer`. Is this right?

Best,
Zheng zhuqing

**Comment by kaukrise** [comment]
There are a lot of options available to you. In FAN-C, some possibilities are:

- Compare the observed/expected matrices instead (you can use `fancplot chr10:40mb-43mb -p mirror -d 2mb AH-1-7-13.hic@50kb@KR AH-2-8-14.hic@50kb@KR -ue -le -uvmax 2 -uvmin -2 -lvmin -2 -lvmax 2`), see [here](https://fan-c.readthedocs.io/en/latest/fancplot-executable/matrix_panel_types.html#mirror) for the docs
- Use `fanc compare` to [compare matrices](https://fan-c.readthedocs.io/en/latest/fanc-executable/fanc-analyse-hic/comparisons.html), scaling them appropriately in the process
- Compare normalised measures derived from the matrices, such as the [insulation score](https://fan-c.readthedocs.io/en/latest/fanc-executable/fanc-analyse-hic/domains.html#insulation-score), instead
- Convert matrices to FAN-C and re-normalise using `fanc hic --deepcopy -n`, then you can use the approach above directly

I am sure there are also a number of different options with tools such as HiCExplorer or Juicer itself!
