### ISSUE TITLE
Some problems of calculate insulation score and install with M1 chip Mac

### ISSUE THREAD

**Issue by ShallyLai** [vaquerizaslab/fanc#69]
Hello, 
Thanks for your good tools, it is an easier way to calculate insulation score, but I still have some problems when using it.
When I type 
 `fanc insulation myFile.hic@10kb myFile.insulation -w 100000`
It appears error message below:
 

> Traceback (most recent call last):
  File "/usr/local/Cellar/python@3.9/3.9.6/Frameworks/Python.framework/Versions/3.9/lib/python3.9/runpy.py", line 188, in _run_module_as_main
    mod_name, mod_spec, code = _get_module_details(mod_name, _Error)
  File "/usr/local/Cellar/python@3.9/3.9.6/Frameworks/Python.framework/Versions/3.9/lib/python3.9/runpy.py", line 147, in _get_module_details
    return _get_module_details(pkg_main_name, error)
  File "/usr/local/Cellar/python@3.9/3.9.6/Frameworks/Python.framework/Versions/3.9/lib/python3.9/runpy.py", line 111, in _get_module_details
    __import__(pkg_name)
  File "/usr/local/lib/python3.9/site-packages/fanc/__init__.py", line 18, in <module>
    from .architecture.domains import InsulationScore, InsulationScores, DirectionalityIndex, \
  File "/usr/local/lib/python3.9/site-packages/fanc/architecture/domains.py", line 4, in <module>
    from ..regions import RegionsTable
  File "/usr/local/lib/python3.9/site-packages/fanc/regions.py", line 68, in <module>
    import tables as t
  File "/usr/local/lib/python3.9/site-packages/tables/__init__.py", line 99, in <module>
    from .utilsextension import (
ImportError: dlopen(/usr/local/lib/python3.9/site-packages/tables/utilsextension.cpython-39-darwin.so, 2): Symbol not found: _blosc_cbuffer_sizes
  Referenced from: /usr/local/lib/python3.9/site-packages/tables/utilsextension.cpython-39-darwin.so
  Expected in: flat namespace
 in /usr/local/lib/python3.9/site-packages/tables/utilsextension.cpython-39-darwin.so

I don't know how to fix this problem and not sure it was caused by the environment or typing error of command line.

BTW, my laptop is MacBook Pro with M1 chip. `Fanc` can not installed with native M1 version python3 because of some unsupported tools, especially `scikit-learn` and `scikit-image.` Also, there are some other tools cannot be installed by pip3, but  they can be solved when searching other website.

Another, I solved the installation problem by using `x86 version` of python3 and its pip .Thus, I am not sure whether the environment or command line error caused error above. 

Thank you.

**Comment by kaukrise** [comment]
Hi, I'm sorry for the issue you encountered. It seems to be a problem with PyTables - it crashes when loading the blosc compression library PyTables depends on. There seem to be similar issues reported on the PyTables GitHub page: https://github.com/PyTables/PyTables/issues/828

Maybe you can find a solution there? I do not have an M1 Mac to test FAN-C on myself.

**Comment by ShallyLai** [comment]
Hello, thanks for your suggestion, I think maybe I successfully installed fanc. 
But when I try to use it, it appeared different error below:  

> /usr/local/opt/python@3.9/bin/python3.9: No module named fanc.__main__; 'fanc' is a package and cannot be directly executed

I type `x86_python3 -m fanc insulation hicpro_Rao.hic@10kb hicpro_Rao.insulation -w 1000000`.
`x86_python3` is the shortcut path of the `x86 version python3` on my laptop which like we type `python3` to run the program.

Do I type wrong?  Or has other problems?

Thank you.

**Comment by kaukrise** [comment]
The `fanc` command line tool is not structured to be run like that (as a module). Instead, it FAN-C provides two executables (`fanc` and `fancplot`) that should be in your `PATH`. What happens if you simply run `fanc -V`? Does it find the executable?

**Comment by kaukrise** [comment]
You could also create a virtual environment with your x86 Python version first and then install FAN-C there, this should ensure that the executables are accessible and use the correct Python interpreter:

```
x86_python3 -m venv venv
source venv/bin/activate
pip install fanc
fanc -V
```

**Comment by ShallyLai** [comment]
Hello, I create a virtual environment and install it successfully, but it still not work.
run `fanc -V`, shows the error below

> Traceback (most recent call last):
  File "/opt/homebrew/bin/fanc", line 4, in <module>
    __import__('pkg_resources').run_script('fanc==0.9.20', 'fanc')
  File "/opt/homebrew/lib/python3.9/site-packages/pkg_resources/__init__.py", line 3243, in <module>
    def _initialize_master_working_set():
  File "/opt/homebrew/lib/python3.9/site-packages/pkg_resources/__init__.py", line 3226, in _call_aside
    f(*args, **kwargs)
  File "/opt/homebrew/lib/python3.9/site-packages/pkg_resources/__init__.py", line 3255, in _initialize_master_working_set
    working_set = WorkingSet._build_master()
  File "/opt/homebrew/lib/python3.9/site-packages/pkg_resources/__init__.py", line 568, in _build_master
    ws.require(__requires__)
  File "/opt/homebrew/lib/python3.9/site-packages/pkg_resources/__init__.py", line 886, in require
    needed = self.resolve(parse_requirements(requirements))
  File "/opt/homebrew/lib/python3.9/site-packages/pkg_resources/__init__.py", line 772, in resolve
    raise DistributionNotFound(req, requirers)
pkg_resources.DistributionNotFound: The 'fanc==0.9.20' distribution was not found and is required by the application

It looks like that fanc still reference to my M1 version python (path is `/opt/homebrew/lib/python3.9/` instead of x86's `/usr/local/lib/python3.9/`)

**Comment by kaukrise** [comment]
Maybe this would work?

```
./venv/bin/fanc -V
```

**Comment by ShallyLai** [comment]
Wow! 
It can be run successfully, I'm very thanks for your help and help me to correctly use virtual environment.

**Comment by kaukrise** [comment]
Great, I'm glad that worked, let me know if you encounter any other issues
