### ISSUE TITLE
Compartment strength

### ISSUE THREAD

**Issue by sespesogil** [vaquerizaslab/fanc#72]
Hi! 

I am using the compartment strength parameter in order to get the values( fanc compartments [--compartment-strength COMPARTMENT_STRENGTH_FILE]. It works fine, but I will appreciate if you can give me an explanation of the result. It print 4 rows with the first one being called "AB-strength" , is that the value I should consider as summarized compartment strength? Which formula are you using?  

Thanks a lot!

S.

**Comment by kaukrise** [comment]
Hey, sure, I have added explanations also to the docs, but here is some more detail:

The calculation of AB compartment strength is described in the supplementary material of the fantastic paper by Flyamer, Gassler, and Imakaev et al. (2017, https://pubmed.ncbi.nlm.nih.gov/28355183): [In a 5x5 compartment enrichment map, ] “to calculate the strength of compartment signal, we took the natural logarithm of the AA * BB / AB^2”. You can find this on page 8 in the Supplementary Material PDF.

This is calculated in FAN-C here:
https://github.com/vaquerizaslab/fanc/blob/03501210239297c6abeaef3510ed926d5e003d0b/fanc/commands/fanc_commands.py#L4063

**Comment by sespesogil** [comment]
Awesome!!! Thanks a lot ! Really appreciate it.

**Comment by kaukrise** [comment]
No worries, thanks for the quick feedback!
