### ISSUE TITLE
convert *.hic file to hicpro file format 

### ISSUE THREAD

**Issue by baishengjun** [vaquerizaslab/fanc#77]
Hi,
I use `fanc dump` to export Hic objects to text files. It output two files, including matrix and region file. I want to get the hicpro file format, should I directly add the bin number at the region file? 
![image](https://user-images.githubusercontent.com/55916074/133721635-903c4ab3-4747-4c31-9f87-cbc4d89e37f1.png)

**Comment by kaukrise** [comment]
Yes, I think so - as far as I remember, numbering starts at 1. But maybe the HiC-Pro GitHub page would be the better place to ask.

**Comment by baishengjun** [comment]
Hi,
Thanks for your quick answer. It seems the matrix was not consistent with the region file, because:
![image](https://user-images.githubusercontent.com/55916074/133765834-ad9777b1-81f5-4c7f-8ade-9d961a7c92e3.png)

**Comment by kaukrise** [comment]
This looks fine to me, can you please be more specific as to what the problem is?

**Comment by baishengjun** [comment]
The matrix file has 61919 bin number, but the region has 61928.

**Comment by kaukrise** [comment]
That just means that there are no interactions in the matrix with bins 61920-61928. It is quite common not to have contacts at the end of chromosomes for mappability reasons. Note that non-zero matrix entries are never reported. Also, just to emphasise this: FAN-C region numbering is 0-based, not 1-based like HiC-Pro.

**Comment by baishengjun** [comment]
Thank you very mych
