### ISSUE TITLE
inquiries about enzyme.

### ISSUE THREAD

**Issue by theshowmustgolangon** [vaquerizaslab/fanc#79]
Hi,

A company which generated Hi-C data told me that they can only provide restriction sites because enzyme names are its own proprietary. Will it be fine to use ones of enzymes with same restriction sites?
4 enzymes are used and their restriction sites are ^GATC, G^ANTC, C^TNAG, T^TAA for forward strand.

**Comment by kaukrise** [comment]
Hi, FAN-C uses BioPython's `Restriction` module to find an enzyme's restriction sites. As far as I can tell, it only uses the restriction site sequence to do this, so you should be fine using enzymes with the same cut sites. See here for details, please: http://biopython.org/DIST/docs/cookbook/Restriction.html#1.3
