### ISSUE TITLE
multiple restriction enzymes

### ISSUE THREAD

**Issue by kimj50** [vaquerizaslab/fanc#8]
Hi,
Thank you for the amazing tool.
I was wondering if the tool is compatible with protocol that uses more than one restriction enzyme.
We use ARIMA kit and the kit uses HinfI and DpnII. 
Thank you,
Jun

**Comment by kaukrise** [comment]
Hi, and thank you!

You can use a custom restriction map in BED format with the `--genome` argument, so this is definitely possible.
At the moment, FAN-C does not let you simply specify multiple restriction enzyme names at once. However, you can still use the built-in tools to make a custom restriction map for your enzyme combination. I'm on my phone, so I can't test this right now, but the following should work:

- First, use `fanc fragments` to build a restriction map for each of your two enzymes separately.
- Combine the two restriction maps using basic Unix tools: `cat /path/to/restriction_map_1.bed /path/to/restriction_map_2.bed | sort -k1,1 -k2,2n | uniq > /path/to/combined_restriction_map.bed` (replace the paths accordingly!)

Then you can use the combined map for `-g` in `fanc auto` or other commands.

Let me know if you need help with any of the commands. I'll see if I can add direct support for multiple restriction enzymes in the next version!

**Comment by kaukrise** [comment]
I have added preliminary support for restriction enzyme cocktails for `fanc fragments`. For now, this is only available via our GitHub repository. I will do some more testing and maybe incorporate this also into `fanc auto` and `fanc pairs` before I bundle this into a relase. But maybe you can clone the repository and install from there for testing?

The syntax is

```
fanc fragments <fasta file> HinfI,DpnII <restriction map (BED)>
```

**Comment by kimj50** [comment]
yup that works.
fanc fragments with two enzyme seems to be working fine and mapping. I'm going to play with the tool for a bit.
Thanks for the quick fix! - Jun

**Comment by kaukrise** [comment]
I have added support for multiple restriction enzymes in the FAN-C subcommands `auto`, `fragments`, `pairs`, and `map` now. My tests with different RE combinations worked fine, but please let me know if you encounter any further issues
