### ISSUE TITLE
Make a bam index file for "fanc pairs"

### ISSUE THREAD

**Issue by Alllium** [vaquerizaslab/fanc#82]
Hi, I'm trying to perform "fanc pairs" (version 0.9.21) using following command: 

fanc pairs \
        foo_1.sort.bam     foo_2.sort.bam \
        foo.pairs  \
        --genome GRCh38.p13.genome.fa   -r MboI \
        --filter-unmappable --filter-multimapping-strict --filter-pcr-duplicates 2 \
        --filter-inward  1000  --filter-outward  1000  

and  "fanc pairs" stopped with following error: 

[E::idx_find_and_load] Could not retrieve index file for 'foo_1.sort.bam'
[E::idx_find_and_load] Could not retrieve index file for 'foo_2.sort.bam'

These bam files are sorted using "samtools sort -n", and I found "samtools" cannnot make index files for queryname-sorted bam files.
Do you know how to make index file of queryname-sorted bam files??
Sorry for my basic question.

Thank you!!

**Comment by kaukrise** [comment]
Hi, are you sure the command stopped at this point? This is usually a warning message issued by `pysam` that cannot be suppressed (at least I have found no way of doing so).

Can you please provide the full log if you are sure the command crashed or exited?

**Comment by Alllium** [comment]
I see. I guess the command stopped after this point, because pairs file (951MB) are generated incompletely.
Anyway I send you the full log: 

2021-09-22 17:41:54,423 INFO FAN-C version: 0.9.21
2021-09-22 17:41:54,425 INFO Getting genome regions (fragments or bins)
2021-09-22 17:41:54,425 INFO Getting regions
2021-09-22 17:46:32,378 INFO Three arguments detected, assuming SAM/BAM input.
[E::idx_find_and_load] Could not retrieve index file for '/home/tnara/MDM/hic/bam/MDM-HiC-06h-Mock-r3_1.sort.bam'
2021-09-22 17:46:32,599 INFO Using filters appropriate for BWA.
[E::idx_find_and_load] Could not retrieve index file for '/home/tnara/MDM/hic/bam/MDM-HiC-06h-Mock-r3_1.sort.bam'
[E::idx_find_and_load] Could not retrieve index file for '/home/tnara/MDM/hic/bam/MDM-HiC-06h-Mock-r3_2.sort.bam'

**Comment by kaukrise** [comment]
It does not look as though the command stopped by itself. It will continually generate and write pairs to the file, and it may look as though nothing is happening for some time. You could try debug mode (`fanc -vvv`) to get more logging output.

**Comment by Alllium** [comment]
I tried the debug mode (fanc -vvv) and found that "fanc pairs" stopped without critical error message.
I checked the way to submit my jobscript and found the way tends to use up memory .
This is not the error of your "fanc pairs", and the probrem is in my jobscript and environment.

Thank you for replying!!
