### ISSUE TITLE
how to generate 0/E matrix

### ISSUE THREAD

**Issue by BioEpi** [vaquerizaslab/fanc#97]
Hello developers of FAN-C,
    I just read your FAN-C paper. FAN-C is a cool tool to analyze Hi-C. I have some questions:
    1: what are and how to generate expected values?
   2: how to generate Correlation matrices?
Would you like to give some explanations?
Best,

<img width="983" alt="image" src="https://user-images.githubusercontent.com/12387462/154781510-0c22aa32-65a5-42b8-99e3-7576f03fa0b3.png">

**Comment by kaukrise** [comment]
Hi, please have a look at the FAN-C documentation:

1. https://fan-c.readthedocs.io/en/latest/fanc-executable/fanc-analyse-hic/oe.html
2. https://fan-c.readthedocs.io/en/latest/fanc-executable/fanc-analyse-hic/ab_compartments.html

I would also recommend diving deeper into the Hi-C literature (you could use the FAN-C paper introduction for references) to gain a better understanding of the concepts you were asking about.
